services:
  - type: web
    name: orbit-x-backend
    env: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_SCHEMA
        sync: false
      - key: GROQ_AI_ENABLED
        value: true
      - key: RABBITMQ_ENABLED
        value: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
