package com.orbitx.backend.messaging.publisher;

import com.orbitx.backend.messaging.dto.AlertEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.AmqpException;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

@Slf4j
@Component
@RequiredArgsConstructor
public class AlertEventPublisher {

    private final RabbitTemplate rabbitTemplate;

    @Value("${orbitx.messaging.exchange}")
    private String exchange;

    @Value("${orbitx.messaging.alerts-routing-key}")
    private String alertsRoutingKey;

    @Value("${orbitx.messaging.thermal-routing-key}")
    private String thermalRoutingKey;

    /**
     * Publishes a general alert event. Used for HIGH and CRITICAL severity alerts
     * generated by the AI prediction engine.
     */
    public void publishAlert(AlertEvent event) {
        try {
            rabbitTemplate.convertAndSend(exchange, alertsRoutingKey, event);
            log.info("Alert event published — id={} severity={} component={}",
                    event.eventId(), event.severity(), event.sourceComponent());
        } catch (AmqpException ex) {
            log.error("Failed to publish alert event id={}: {}", event.eventId(), ex.getMessage());
            // Swallowed intentionally: alert publishing must not break the API response
        }
    }

    /**
     * High-priority lane for thermal threshold breaches.
     * Routes to the thermal queue which has higher consumer priority.
     */
    public void publishThermalCritical(AlertEvent event) {
        try {
            rabbitTemplate.convertAndSend(exchange, thermalRoutingKey, event);
            log.warn("THERMAL CRITICAL event published — temp={}°C prob={}",
                    event.currentTemperatureCelsius(), event.overheatProbability());
        } catch (AmqpException ex) {
            log.error("Failed to publish thermal event: {}", ex.getMessage());
        }
    }
}
